name: softorium_daily_planner
description: test assignment for softorium.ru
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  cupertino_icons:
  provider:
  freezed:
  freezed_annotation:
  json_annotation:
  json_serializable:
  flutter_svg:
  intl:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
scripts:
  rebuild: dart run build_runner build --delete-conflicting-outputs
  translate: flutter gen-l10n