name: softorium_daily_planner
description: test assignment for softorium.ru
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  cupertino_icons:
  provider:
  freezed:
  freezed_annotation:
  json_annotation:
  json_serializable:
  flutter_svg:
  intl:
  hive:
  path_provider:
  uuid:
  smooth_page_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  test:
  flutter_lints:
  build_runner:
  flutter_native_splash:
  mocktail:

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#C8C7F9"
  color_dark: "#C8C7F9"
  image: assets/images/transparent.png
  android_12:
    icon_background_color: "#C8C7F9"
    icon_background_color_dark: "#C8C7F9"
    image: assets/images/transparent.png  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
     
scripts:
  rebuild: dart run build_runner build --delete-conflicting-outputs
  translate: flutter gen-l10n